name: comrade
favicon: null
layout_spectrum: 0.1731
typography_spectrum: 0.65043
title: comrade
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bfbfbf'
    - '#b9b9b9'
    - '#aaaaaa'
    - '#000000'
    - '#b6b6b6'
  brandStrength: 0
  lightness: 0.5673295925371349
  saturation: 0
  rhythmicContrast: 0.2982035370077938
purpose: []
